LuckyVicky-2team/frontend

README.md
package-lock.json
package.json
src/components/Test.tsx

feat: readme & library
readme에 사용된 라이브러리들 및 버전 정보 적어놓음
(추가적으로 필요할시 수정해주세요.)
library에 data state 들 볼수있는 react-query-devtools 설치
(Provider로 app 컴포넌트 감싸주는 작업이 추가로 필요)

feat: readme & library

---

src/apis/instance.ts

어떤 변경 사항이 있나요?
-   [ ] 버그 수정
-   [ ] 문서 수정
- axios 인스턴스 생성
- 아직 base URL 이 없어서 나중에 환경변수로 추가하면 될 것 같습니다.
>

feat: axios instanse 생성

---

src/components/Test.tsx

어떤 변경 사항이 있나요?
-   [✔️] 새로운 기능 추가
-   [ ] 버그 수정
-   [x] 코드 리팩토링
-   [x] 문서 수정
discord- github webhook 연동 테스트
깃헙 내부에 settings > webhook 이라는 탭이있어 .yaml 파일에 따로 안적고 일단 시도해 보았습니다

feat:webhook action test

---

src/app/layout.tsx
src/components/ReactQueryProvider.tsx

어떤 변경 사항이 있나요?
-   [ ] 버그 수정
-   [ ] 문서 수정
- 리액트 쿼리 설정
>

feat: 리액트 쿼리 설정

---

package-lock.json
package.json

어떤 변경 사항이 있나요?
-   [ ] 버그 수정
-   [x] 문서 수정
>

chore: install husky, lint-staged, prettier

---

src/components/common/Tag/Tag.module.scss
src/components/common/Tag/index.tsx

어떤 변경 사항이 있나요?
-   [ ] 버그 수정
-   [ ] 문서 수정
태그 컴포넌트
- #35 
>
> 자세한 css는 디자인이 나오면 변경하겠습니다.

[Feat] Tag 컴포넌트

---

src/app/(authentication)/signin/page.tsx

어떤 변경 사항이 있나요?
-   [ ] 버그 수정
-   [x] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
-   [ ] 문서 수정
>

Fix: 소셜 로그인 URL 수정

---

src/app/main/_components/Header/Header.module.scss
src/app/main/_components/Header/Header.tsx
src/app/mypage/_components/Info/Info.tsx
src/app/mypage/_components/Info/info.module.scss
src/app/mypage/page.tsx

어떤 변경 사항이 있나요?
-   [ ] 버그 수정
-   [ ] 문서 수정
헤더에 로그인 안했을시 로그인버튼추가
마이페이지 로그아웃 기능 추가
>

Feat : Header에 로그인 & 마이페이지에서 로그아웃 추가

---

src/components/common/IconButton/index.tsx

어떤 변경 사항이 있나요?
-   [ ] 버그 수정
-   [x] 코드 리팩토링
-   [ ] 문서 수정
IconButton이 사이즈가 다양해야할 경우가 생겨 사이즈 설정을 변경했습니다.
1. size prop 선택 : 'xsmall' | 'small' | 'medium' | 'large'
2. size 선택안할시 : 반드시 className prop 으로 width,height 전달해주세요
사용예시
1.  <IconButton size="medium"/>
2.
Example.tsx
import styles from "Example.module.scss"
export default function Example(){ return ( <IconButton className={styles.example}/> ) }
Example.module.scss
.example {
width:40px;
height:40px;
}

Refactor: IconButton size 설정 변경

---

next.config.mjs

어떤 변경 사항이 있나요?
-   [x] 버그 수정
-   [ ] 문서 수정
예진님 프론트엔드 개발서버 안된다고 하셔서 빠른 수정하였습니다
>

Update next.config.mjs 원상복구

---

src/components/common/TagInput/index.tsx

어떤 변경 사항이 있나요?
-   [x] 버그 수정
-   [ ] 문서 수정
- 회원가입 TagInput '빈 값' 에 대한 오류가 계속 나오는 이슈 해결
#40 
>

Fix: 회원가입 TagInput 핫픽스

---

src/app/gatherings/_components/Card/index.tsx

어떤 변경 사항이 있나요?
-   [ ] 버그 수정
-   [ ] 문서 수정
>

Feat:모임목록 이미지 눌러도 상세로 들어가게 변경 & selectDropdown uI

---

src/app/other-profile/[id]/_components/OtherProfileContents/index.tsx

어떤 변경 사항이 있나요?
-   [x] 버그 수정
-   [ ] 문서 수정
- pr 태그가 없을 시 0이 출력되는 문제 해결
>

Fix: 다른 사람 프로필 페이지 핫픽스

---

src/app/(authentication)/_components/AuthTagInput/index.tsx
src/components/common/SaveGatheringButton/index.tsx

어떤 변경 사항이 있나요?
-   [x] 버그 수정
-   [ ] 문서 수정
>

Fix: 찜 버튼 오류 해결

---

src/api/apis/reviewApis.ts
src/api/queryHooks/review.ts
src/app/mypage/review/(gatherings)/[gatheringId]/[revieweeId]/page.tsx
src/app/mypage/review/_components/reveicedReviewItem/MannerList.tsx
src/app/mypage/review/_components/reveicedReviewItem/ReceivedReviewItem.module.scss
src/app/mypage/review/receivedReviews/ReceivedReviews.module.scss
src/app/mypage/review/receivedReviews/page.tsx
src/types/response/ReviewRES.ts
src/utils/QueryKey.ts

어떤 변경 사항이 있나요?
-   [ ] 버그 수정
-   [ ] 문서 수정
리뷰 부분 끝났습니다!
>

Feat: mypage review 내가받은 리뷰 api 적용

---

src/app/mypage/review/_components/reveicedReviewItem/MannerList.module.scss
src/app/mypage/review/_components/reveicedReviewItem/ReceivedReviewItem.module.scss
src/app/mypage/review/receivedReviews/ReceivedReviews.module.scss

어떤 변경 사항이 있나요?
-   [ ] 버그 수정
-   [ ] 문서 수정
css 만 살짝 수정했습니다!
>

Style:css 약간 수정

---

src/app/(authentication)/signin/page.tsx
src/components/common/FindPlaceModal/KakaoMap/index.tsx
src/utils/isPC.ts

어떤 변경 사항이 있나요?
-   [ ] 버그 수정
-   [x] 주석 추가 및 수정
-   [ ] 문서 수정
- 소셜로그인 주석 처리 
- userAgent 이용한 PC 확인 후 지도 스크롤 기능 추가
>

Feat: 소셜로그인 주석 처리 / userAgent 이용한 PC 확인 후 지도 스크롤 기능 추가

---

src/app/mypage/myFavoriteGatherings/myFavoriteGatherings.module.scss
src/app/other-profile/[id]/_components/OtherProfileContents/OtherEvaluationTags/EvaluationgTag/EvaluationTag.module.scss
src/app/other-profile/[id]/_components/OtherProfileContents/OtherProfileContents.module.scss
src/app/other-profile/[id]/_components/OtherProfileContents/index.tsx
src/components/common/AccessControlBoundary/index.tsx

어떤 변경 사항이 있나요?
-   [ ] 버그 수정
-   [ ] 문서 수정
- 다른 유저 프로필 / 나의 찜 페이지 반응형
>

Design: 다른 유저 프로필 / 나의 찜 페이지 반응형

---

src/app/(authentication)/_components/AuthHeader/AuthHeader.module.scss
src/app/(authentication)/_components/AuthHeader/index.tsx

어떤 변경 사항이 있나요?
-   [ ] 버그 수정
-   [ ] 문서 수정
- AuthHeader 과 기존 Header 디자인 다른 것 변경
>

Design: AuthHeader 디자인 변경

---

src/app/(authentication)/_components/AuthHeader/AuthHeader.module.scss

어떤 변경 사항이 있나요?
-   [ ] 버그 수정
-   [ ] 문서 수정
>

Design: AuthHeader 반응형 디자인 재수정

---

src/app/(authentication)/signin/page.tsx

어떤 변경 사항이 있나요?
-   [ ] 버그 수정
-   [ ] 문서 수정
- 소셜로그인 테스트를 위한 소셜로그인 버튼 생성
>

Hotfix: 소셜로그인 버튼생성

---

src/api/instance.ts
src/app/(authentication)/_components/AuthTagInput/AuthTagInput.module.scss
src/app/(authentication)/_components/AuthTagInput/index.tsx
src/app/(authentication)/_components/SignupForm/ConsentForm/TermsItem/index.tsx
src/app/(authentication)/_components/SignupForm/EmailSignupForm/EmailSignupForm.module.scss
src/app/(authentication)/_components/SignupForm/SocialSignupForm/SocialSignupForm.module.scss
src/app/(authentication)/_components/SignupForm/SocialSignupForm/index.tsx
src/app/gatherings/[id]/_components/Members/index.tsx
src/app/other-profile/[id]/page.tsx
src/app/threads/[gatheringId]/page.tsx
src/app/threads/_components/ThreadInput/index.tsx
src/app/threads/page.tsx
src/components/common/ToastList/ToastList.module.scss
src/utils/getFormattedDate.ts

어떤 변경 사항이 있나요?
-   [x] 버그 수정
-   [x] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
-   [ ] 문서 수정
- Axios Interceptor 수정 및 소셜 회원가입 토큰 수정
- 약관 동의 디자인 수정
- 푸시 알림 동의 및 철회 시 토스트 생성
>

Fix: Axios Interceptor 수정 및 약관동의 디자인 수정

---

src/actions/AuthActions.ts
src/api/apis/authApis.ts
src/api/instance.ts
src/app/(authentication)/_components/SignupForm/SocialSignupForm/index.tsx
src/app/main/_components/Footer/Footer.tsx
src/app/main/page.tsx
src/app/threads/_components/ChattingRoom/index.tsx
src/utils/getNewAccessToken.ts

어떤 변경 사항이 있나요?
- 리프레시 토큰 로직 수정
- 채팅방 https 로 변경
>

Refactor: 리프레시 토큰 로직 수정

---

src/actions/AuthActions.ts
src/api/instance.ts
src/utils/getNewAccessToken.ts

어떤 변경 사항이 있나요?
- 현재 dev 에서 리프레시 토큰 관련 무한로딩 오류가 발견되어서 급하게 수정했습니다!
- 오류관련이라 확인되시면 바로 merge 해주셔도 될 것 같습니다.
>

Hotfix: 리프레시 토큰 오류 수정

---

src/components/common/AppInstallPrompt/index.tsx

Fix: songeun-9

---

src/app/(authentication)/_components/SignupForm/EmailSignupForm/index.tsx
src/app/(authentication)/_components/SignupForm/SocialSignupForm/index.tsx
src/app/threads/_components/ChattingRoom/index.tsx

Fix: 채팅방 스크롤 오류 수정 및 디버깅용 주석 추가

---

.gitignore
netlify.toml
package-lock.json
package.json
src/app/api/convert-gif-to-mp4/route.ts

어떤 변경 사항이 있나요?
netlify.toml 파일에 node modules 포함
Netlify cli 설치
>

Fix: songeun-13

---

src/actions/AuthActions.ts
src/app/(authentication)/_components/SignupForm/SocialSignupForm/index.tsx
src/app/threads/_components/ChattingRoom/index.tsx
src/app/threads/_components/TalkListItem/index.tsx

어떤 변경 사항이 있나요?
- 소셜회원가입 디버깅 코드 추가
>

Fix: 소셜회원가입 디버깅 코드 추가

---

src/actions/AuthActions.ts
src/api/instance.ts
src/app/(authentication)/_components/SignupForm/SocialSignupForm/index.tsx

어떤 변경 사항이 있나요?
- 소셜 회원가입 디버깅 코드 추가
>

Fix: 소셜 회원가입 디버깅 코드 추가

---

src/app/(authentication)/_components/SignupForm/SocialSignupForm/index.tsx

어떤 변경 사항이 있나요?
- 소셜 회원가입 디버깅 코드 추가 - 3
>

Fix: 소셜 회원가입 디버깅 코드 추가 - 3

---

src/actions/AuthActions.ts
src/api/apis/authApis.ts
src/api/instance.ts
src/app/(authentication)/_components/SignupForm/SocialSignupForm/index.tsx
src/components/common/SaveGatheringButton/index.tsx
src/types/request/authRequestTypes.d.ts

어떤 변경 사항이 있나요?
- 소셜 회원가입 오류 수정 및 찜버튼 오류 수정
>

Fix: 소셜 회원가입 오류 수정 및 찜버튼 오류 수정

---

src/api/instance.ts

어떤 변경 사항이 있나요?
- 소셜 회원가입 오류 재수정
>

Fix: 소셜 회원가입 오류 재수정

---

src/actions/AuthActions.ts
src/app/(authentication)/_components/SignupForm/SocialSignupForm/index.tsx

어떤 변경 사항이 있나요?
- 소셜 회원가입 디버깅 코드 추가
>

Fix: 소셜 회원가입 디버깅 코드 추가 - 4

---

src/actions/AuthActions.ts
src/app/(authentication)/_components/SignupForm/SocialSignupForm/index.tsx

어떤 변경 사항이 있나요?
- 소셜 회원가입 디버깅 코드 추가
>

Fix: 소셜 회원가입 디버깅 코드 추가 - 5

---

global.d.ts
src/app/gatherings/[id]/_components/Footer/index.tsx
src/app/gatherings/[id]/_components/GatheringDetails.tsx/GatheringDetails.module.scss
src/app/gatherings/[id]/_components/GatheringForm/GatheringForm.module.scss
src/app/gatherings/[id]/_components/GatheringForm/index.tsx
src/app/gatherings/[id]/_components/Members/Members.module.scss
src/app/gatherings/[id]/_components/Members/index.tsx
src/app/gatherings/new/_components/GameDataList/GameDataList.module.scss
src/app/gatherings/new/_components/GameDataList/index.tsx
src/app/gatherings/new/_components/NumberInput/NumberInput.module.scss
src/app/globals.scss
src/components/common/AppInstallPrompt/MobileInstallPrompt/MobileInstallPrompt.module.scss
src/components/common/AppInstallPrompt/MobileInstallPrompt/index.tsx
src/components/common/AppInstallPrompt/index.tsx
src/components/common/BottomSheet/BottomSheet.module.scss
src/components/common/FCMDisabledPrompt/index.tsx
src/components/common/Modal/index.tsx
src/hooks/useScreenHeight.ts
src/utils/getCookie.ts

어떤 변경 사항이 있나요?
members 바텀시트 전체적인 사이즈 작게 조정
모임 만들기 전체적인 사이즈 작게 조정
텍스트 에디터 사이즈 작게 조정 (모바일)
앱 설치 프롬프트 30일간 안 보기 기능 추가, firefox 예외 처리, ios 앱 설치여부 검사 후 프롬프트 띄우기
#185 
>

Fix: songeun 14

---

src/app/gatherings/[id]/_components/Footer/index.tsx
src/app/layout.tsx
src/components/common/AppInstallPrompt/index.tsx
src/components/common/BottomSheet/index.tsx

어떤 변경 사항이 있나요?
사파리에서 푸터 아래 공백이 생기는 현상 해결
사파리에서 주소바에 따라 바텀시트 높이 조정
아이폰 앱 설치 여부 확인 로직 제거 (불가능한 방법)
#187 
>

Fix: songeun-15

---

src/app/gatherings/_components/Card/Card.module.scss

[Refactor] 글자 단어 단위로 다음줄로 넘기기

---

src/api/apis/logOutApis.ts
src/app/(authentication)/_components/AuthHeader/AuthHeader.module.scss
src/app/(authentication)/_components/SigninForm/index.tsx
src/app/(authentication)/_components/SignupForm/EmailSignupForm/EmailSignupForm.module.scss
src/app/(authentication)/_components/SignupForm/EmailSignupForm/index.tsx
src/app/(authentication)/_components/SignupForm/SocialSignupForm/SocialSignupForm.module.scss
src/app/(authentication)/_components/SignupForm/SocialSignupForm/index.tsx
src/app/NotFoundPage.module.scss
src/app/mypage/_components/Info/Info.tsx
src/app/mypage/myFavoriteGatherings/page.tsx
src/app/not-found.tsx
src/app/threads/[chatRoomId]/ThreadDetailPage.module.scss
src/app/threads/_components/ChattingRoom/ChattingRoom.module.scss
src/app/threads/_components/ChattingRoom/index.tsx
src/components/common/Modal/LoginModal/index.tsx
src/components/common/ToastList/ToastList.module.scss
src/contexts/toastContext.tsx

어떤 변경 사항이 있나요?
- 회원가입 및 로그인 시 확인 버튼 클릭 시 미입력 사항 보여주기
- 로그아웃 오류 수정
- 채팅방 로딩 중 채팅 전송 금지
- 404 페이지 디자인 수정
- 토스트 갯수 3개 제한 및 글씨 크기 수정
- sticky 부분 전체 fixed 로 변경
>

Fix: 각종 오류 및 디자인 변경

---

src/app/mypage/review/(gatherings)/[gatheringId]/GatheringID.module.scss
src/app/mypage/review/(gatherings)/[gatheringId]/page.tsx
src/app/mypage/review/_components/GatheringItem/GatheringItem.module.scss
src/app/mypage/review/_components/GatheringItem/index.tsx
src/app/mypage/review/_components/MyReviewItem/MyReviewItem.module.scss
src/app/mypage/review/_components/MyReviewItem/index.tsx

어떤 변경 사항이 있나요?
- [] 코드 리팩토링
- 받은리뷰에서 긍정리뷰가 파란색, 부정리뷰가 빨간색으로 변경
- 모임 리뷰 detail page에서(작성/확인) '모임리뷰'라는 디폴트 문구 삭제
- 받은 리뷰 없을시 ui 안내
- 모임 리뷰 detail page 이미지 비율 꺠지는 것 수정 
>

Fix: 모임 리뷰 qa

---

src/api/instance.ts
src/app/(authentication)/_components/SigninForm/index.tsx
src/app/(authentication)/_components/SignupForm/SocialSignupForm/index.tsx
src/app/layout.tsx
src/app/main/_components/Header/Header.tsx
src/app/main/page.tsx
src/app/mypage/_components/Info/Info.tsx
src/app/threads/_components/ChattingRoom/index.tsx
src/components/common/AccessControlBoundary/index.tsx
src/components/common/AppInstallPrompt/index.tsx
src/hooks/useScreenHeight.ts
src/utils/changeAccessToken.ts
src/utils/getCookie.ts

어떤 변경 사항이 있나요?
- 채팅방 모바일 ui 수정
- AccessControlBoundary 컴포넌트로 인한 CSR 수정
- 헤더 수정
- 찜 갯수 동기화
- 로그인 상태 동기화
** 충돌 주의 **
이하 파일들 수정해서 충돌 발생할 수 있으니 참고해주세요!
- layout.js
- main 페이지
- Header 컴포넌트
- AppInstallPrompt 컴포넌트
- 마이페이지 Info 컴포넌트
>

Fix: qa 수정 및 오류 수정

---

src/app/gatherings/_components/Card/index.tsx

어떤 변경 사항이 있나요?
- 모임목록 이미지 lazy loading 처리
>

Fix: 이미지 lazy loading

---

src/api/apis/gatheringsApis.ts
src/app/gatherings/Gatherings.module.scss
src/app/gatherings/GatheringsPageClient.tsx
src/app/gatherings/_components/Filter/index.tsx
src/app/gatherings/_components/GatheringList/GatheringListClient.tsx
src/app/gatherings/_components/GatheringList/index.tsx
src/app/gatherings/page.tsx
src/app/threads/_components/ChattingRoom/index.tsx
src/components/common/SelectBox/index.tsx
src/hooks/useInfiniteGatheringsQuery.ts

어떤 변경 사항이 있나요?
- [] 버그 수정
모임목록에서 ssr이 안되고있어서 느렸던 것으로 판단됩니다
- 리팩토링 후 로직 : 
서버 컴포넌트에서 partial SSR이 진행되는 동안 (csr 부분의 infiniteQuery가 받아올 데이터를, ssr로 prefetchInfiniteQuery로 10개만 먼저 받아와서 빠르게 초기 HTML 내려준다는 의미), 
UI 요소들은 먼저 렌더링되어 보여지고, 
그 뒤 prefetchGatheringPage로 전달된 서버 컴포넌트가 준비되면 Suspense를 통해 해당 목록이 표시되는 구조입니다.
이후 GatheringListClient에서는 useInfiniteQuery를 통해 추가 페이지 데이터를 가져오는 식으로 확장됩니다.
> 개선된 점
- 기존 LCP (7초대) 대비 개선 후 0.7~0.9초대로 감소
- lighthouse 전체적인 점수도 60점대에서 97~99점으로 증가
이후에는 상황별 추천에도 ssr 적용해볼 예정입니다. 
코드에 이상한 점이 있다면 편하게 리뷰해 주시면 반영하겠습니다..!
Suspense를 사용한 만큼 useInfiniteQuery 대신 useSuspenseInfiniteQuery를 쓰려고 했는데 에러가 나서 찾아보니
useSuspense 시리즈(useSuspense, useSuspenseInfiniteQuery) 가 아직 문제가 많은것같아 제외하였습니다. 
추후 안정화 되면 적용해보겠습니다~ 
>
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 …

Refactor : 모임목록

---

src/app/api/convert-gif-to-webp/route.ts
src/app/gatherings/_components/Card/index.tsx
src/utils/gifToMp4.module.scss
src/utils/gifToWebp.tsx
src/utils/gifTransform.module.scss

어떤 변경 사항이 있나요?
- 모임목록
gif가 있으면 kb 용량이 아닌 MB로 나와서 gif를 webp 포맷으로 변경했습니다.
기존에 설치된 sharp library 사용했고, webp 에서 animation 을 지원해서 형식만 다르고 원본 gif 처럼 보입니다!
로컬에서 테스트 시에는 이미지 용량 1.2MB -> 200kb 정도로 줄어들었습니다
>

Hoxfix : 모임목록 gif -> webp 포맷변경

---

build.sh

어떤 변경 사항이 있나요?
vercel에 배포하기 위한 설정
>

Create build.sh 
